### PR TITLE
Set generated class package to namespace instead of applicationId

### LINKED ISSUE #8: Incompatible with `applicationIdSuffix`
The generated classes have package resolved from `applicationId` + `applicationIdSuffix` which breaks compatibility between different build variants.

For example:

```kotlin
// app module build.gradle.kts

android {
  namespace = "com.example.app.android"

  defaultConfig {
    applicationId = "com.example.app"
  }

  buildTypes {
    debug {
      applicationIdSuffix = ".debug"
    }
    release {
      applicationIdSuffix = ".release"
    }
  }
}

bytemaskConfig {
  className.set("BytemaskConfig")
}
```

- For `debug` build type, the generated class will be generated as `com.example.app.debug.BytemaskConfig`
- For `release` build type, the generated class will be generated as `com.example.app.release.BytemaskConfig`

This breaks binary compatibility between build variants and project will not compile after switching between build types.

I think the solution would be either to:
- generate class in namespace package (like AGP does with BuildConfig), or
- let user specify package for generated class

### PR DESCRIPTION
**Pull request by matejsemancik**
Resolves #8

### CODE REVIEW

**Review by PatilShreyas — APPROVED** [review]
Thank you @matejsemancik for the contribution. Changeset looks good to me 😃 👍🏻

**Comment by PatilShreyas** [comment]
@matejsemancik can you please reformat this with spotless? 

just run `./gradlew spotlessApply` and commit the changes. Please have a look at [contributing.md](https://github.com/PatilShreyas/bytemask/blob/main/CONTRIBUTING.md) for more info

**Comment by matejsemancik** [comment]
Ah, I missed that, will do!

**Comment by matejsemancik** [comment]
I think I'm also gonna ditch the applicationSuffix configuration from sample app, because with current build setup the app will use the current plugin version (1.0.0-alpha01) which does not support the change and build will fail.

**Comment by PatilShreyas** [comment]
> I think I'm also gonna ditch the applicationSuffix configuration from sample app, because with current build setup the app will use the current plugin version (1.0.0-alpha01) which does not support the change and build will fail.

Sure 👍🏻

**Pull request merged**
